import type { Metadata } from 'next'
import './globals.css'
import { Inter, Jura } from "next/font/google";
import {AccountAbstractionProvider} from '../context/accountAbstractionContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AccountAbstractionProvider>
          {children}
        </AccountAbstractionProvider>
      </body>
    </html>
  )
}
